import { Body, Controller, Get, Param, Post, Patch, Delete, Req, Res, UnauthorizedException } from '@nestjs/common';
import { AccountService } from './account.service';
import { CreateAccountDto } from './dto/create-account.dto';
import { LoginDto } from './dto/login.dto';
import { ApiTags, ApiOperation, ApiBody, ApiOkResponse, ApiCreatedResponse, ApiParam } from '@nestjs/swagger';
import { AccountResponseDto } from './dto/account-response.dto';
import { ResetPasswordDto } from './dto/reset-password.dto';
import { Request, Response } from 'express';

function parseCookie(req: Request) {
  const header = req.headers.cookie;
  if (!header) return {};
  return header.split(';').map(s => s.trim()).reduce((acc: any, cur) => {
    const [k, v] = cur.split('='); acc[k] = v; return acc;
  }, {});
}

@ApiTags('Accounts')
@Controller('accounts')
export class AccountController {
  constructor(private svc: AccountService) {}

  @Get()
  @ApiOperation({ summary: 'Get all accounts (password excluded)' })
  @ApiOkResponse({ type: [AccountResponseDto] })
  getAll() {
    return this.svc.getAll();
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get account by id (password excluded)' })
  @ApiParam({ name: 'id' })
  @ApiOkResponse({ type: AccountResponseDto })
  getById(@Param('id') id: string) {
    return this.svc.getById(id);
  }

  @Post()
  @ApiOperation({
    summary: 'Create account',
    description: 'Account is always created with lifecycle = CREATED, must_change_password = true, password_last_changed = null. Initial password is generated by system.',
  })
  @ApiBody({ type: CreateAccountDto })
  @ApiCreatedResponse({
    schema: {
      properties: {
        account: { $ref: '#/components/schemas/AccountResponseDto' },
        initial_password: { type: 'string' },
      },
    },
  })
  create(@Body() body: CreateAccountDto) {
    return this.svc.add(body as any);
  }

  @Post('login')
  @ApiOperation({
    summary: 'Login (sets cookie accountId)',
    description: 'If lifecycle=CREATED, response is 200 with must_change_password=true. DISABLED/EXPIRED => 403. DELETED => 404.',
  })
  @ApiBody({ type: LoginDto })
  @ApiOkResponse({ type: AccountResponseDto })
  async login(@Body() body: LoginDto, @Res({ passthrough: true }) res: Response) {
    const acc = await this.svc.login(body.username, body.password);
    // set cookie accountId
    res.cookie('accountId', acc.id, { httpOnly: true });
    return acc;
  }

  @Post('logout')
  @ApiOperation({ summary: 'Logout (clears cookie accountId)' })
  logout(@Res({ passthrough: true }) res: Response) {
    res.clearCookie('accountId');
    return { ok: true };
  }

  @Get('validate')
  @ApiOperation({ summary: 'Validate cookie and return account' })
  @ApiOkResponse({ type: AccountResponseDto })
  async validate(@Req() req: Request) {
    const cookies = parseCookie(req);
    const id = cookies['accountId'];
    if (!id) throw new UnauthorizedException('accountId cookie not present');
    return this.svc.validateCookie(id);
  }

  @Post(':id/reset-password')
  @ApiOperation({
    summary: 'Reset password (admin or self)',
    description: 'If lifecycle=CREATED and password change succeeds, lifecycle becomes ACTIVE; must_change_password=false; password_last_changed set.',
  })
  @ApiBody({ type: ResetPasswordDto })
  resetPassword(@Param('id') id: string, @Body() body: ResetPasswordDto) {
    return this.svc.resetPassword(id, body.newPassword);
  }

  @Patch(':id/role')
  @ApiOperation({ summary: 'Edit account role' })
  editRole(@Param('id') id: string, @Body('roleLookupId') roleLookupId: string) {
    return this.svc.editRole(id, roleLookupId);
  }

  @Patch(':id/disable')
  @ApiOperation({ summary: 'Disable account' })
  disable(@Param('id') id: string) {
    return this.svc.setLifecycle(id, 'DISABLED');
  }

  @Patch(':id/enable')
  @ApiOperation({ summary: 'Enable account' })
  enable(@Param('id') id: string) {
    return this.svc.setLifecycle(id, 'ACTIVE');
  }

  @Delete(':id')
  @ApiOperation({ summary: 'Soft delete account (mark DELETED)' })
  delete(@Param('id') id: string) {
    return this.svc.softDelete(id);
  }
}
