import { Body, Controller, Get, Param, Post, Patch, Delete, Req, Res, UnauthorizedException } from '@nestjs/common';
import { AccountService } from './account.service';
import { CreateAccountDto } from './dto/create-account.dto';
import { LoginDto } from './dto/login.dto';
import {
  ApiTags,
  ApiOperation,
  ApiBody,
  ApiOkResponse,
  ApiCreatedResponse,
  ApiParam,
  ApiBadRequestResponse,
  ApiUnauthorizedResponse,
  ApiForbiddenResponse,
  ApiNotFoundResponse,
  ApiConflictResponse,
} from '@nestjs/swagger';
import { AccountResponseDto } from './dto/account-response.dto';
import { ResetPasswordDto } from './dto/reset-password.dto';
import { Request, Response } from 'express';
import { EditRoleDto } from './dto/edit-role.dto';
import { EditAccountDto } from './dto/edit-account.dto';
import { Serialize } from '../common/decorators/serialize.decorator';
import { ApiErrorResponseDto } from '../common/dto/api-error-response.dto';
import { OkResponseDto } from '../common/dto/ok-response.dto';
import { AccountCreateResponseDto } from './dto/account-create-response.dto';
import { ApiNotFoundResponseDto } from 'src/common/dto/api-error-notfound.dto';
import { AccountListResponseDto } from './dto/account-list-response.dto';
import { AccountGetResponseDto } from './dto/account-get-response.dto';
import { AccountLoginResponseDto } from './dto/account-login-response.dto';
import { AccountValidateResponseDto } from './dto/account-validate-response.dto';
import { AccountResetPasswordResponseDto } from './dto/account-reset-password-response.dto';
import { ChangePasswordDto } from './dto/change-password.dto';
import { AccountChangePasswordResponseDto } from './dto/account-change-password-response.dto';
import { AccountEditRoleResponseDto } from './dto/account-edit-role-response.dto';
import { AccountEditResponseDto } from './dto/account-edit-response.dto';
import { AccountLifecycleResponseDto } from './dto/account-lifecycle-response.dto';
import { AccountDeleteResponseDto } from './dto/account-delete-response.dto';

function parseCookie(req: Request) {
  const header = req.headers.cookie;
  if (!header) return {};
  return header.split(';').map(s => s.trim()).reduce((acc: any, cur) => {
    const [k, v] = cur.split('='); acc[k] = v; return acc;
  }, {});
}

@ApiTags('Accounts')
@Controller('accounts')
export class AccountController {
  constructor(private svc: AccountService) {}

  @Get()
  @ApiOperation({ summary: 'Get all accounts (password excluded)' })
  @ApiOkResponse({ type: [AccountListResponseDto] })
  @Serialize(AccountListResponseDto)
  getAll() {
    return this.svc.getAll();
  }

  @Get('validate')
  @ApiOperation({ summary: 'Validate cookie and return account' })
  @ApiOkResponse({ type: AccountValidateResponseDto })
  @ApiBadRequestResponse({ type: ApiErrorResponseDto, description: 'Invalid UUID format' })
  @ApiUnauthorizedResponse({ type: ApiErrorResponseDto, description: 'Invalid or missing cookie' })
  @Serialize(AccountValidateResponseDto)
  async validate(@Req() req: Request) {
    const cookies = parseCookie(req);
    const id = cookies['accountId'];
    console.log('Validating accountId from cookie:', id);
    if (!id) throw new UnauthorizedException('accountId cookie not present');
    return this.svc.validateCookie(id);
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get account by id (password excluded)' })
  @ApiParam({ name: 'id' })
  @ApiOkResponse({ type: AccountGetResponseDto })
  @ApiBadRequestResponse({ type: ApiErrorResponseDto, description: 'Invalid UUID format' })
  @ApiNotFoundResponse({ type: ApiNotFoundResponseDto, description: 'Account not found' })
  @Serialize(AccountGetResponseDto)
  getById(@Param('id') id: string) {
    return this.svc.getById(id);
  }

  @Post()
  @ApiOperation({
    summary: 'Create account',
    description: 'Account is always created with lifecycle = CREATED, must_change_password = true, password_last_changed = null. Initial password is generated by system.',
  })
  @ApiBody({ type: CreateAccountDto })
  @ApiCreatedResponse({ type: AccountCreateResponseDto })
  @ApiBadRequestResponse({
    type: ApiErrorResponseDto,
    description: 'Validation failed (missing/invalid fields)',
    schema: {
      example: {
        statusCode: 400,
        error: 'Bad Request',
        message: 'Validation failed',
        details: [{ field: 'username', message: 'username is required' }],
      },
    },
  })
  @ApiConflictResponse({
    type: ApiErrorResponseDto,
    description: 'Username already exists',
    schema: {
      example: {
        statusCode: 409,
        error: 'Conflict',
        message: 'Username already exists',
        details: [{ field: 'username', message: 'Username already exists' }],
      },
    },
  })
  @Serialize(AccountCreateResponseDto)
  create(@Body() body: CreateAccountDto) {
    return this.svc.add(body as any);
  }

  @Post('login')
  @ApiOperation({
    summary: 'Login (sets cookie accountId)',
    description: 'If lifecycle=CREATED, response is 200 with must_change_password=true. DISABLED/EXPIRED => 403. DELETED => 404.',
  })
  @ApiBody({ type: LoginDto })
  @ApiOkResponse({ type: AccountLoginResponseDto })
  @ApiUnauthorizedResponse({ type: ApiErrorResponseDto, description: 'Invalid credentials' })
  @ApiForbiddenResponse({ type: ApiErrorResponseDto, description: 'Account disabled or expired' })
  @ApiNotFoundResponse({ type: ApiErrorResponseDto, description: 'Account deleted' })
  @Serialize(AccountLoginResponseDto)
  async login(@Body() body: LoginDto, @Res({ passthrough: true }) res: Response) {
    const acc = await this.svc.login(body.username, body.password);
    // set cookie accountId
    res.cookie('accountId', acc.id, { httpOnly: true });
    return acc;
  }

  @Post('logout')
  @ApiOperation({ summary: 'Logout (clears cookie accountId)' })
  @ApiOkResponse({ type: OkResponseDto })
  @Serialize(OkResponseDto)
  logout(@Res({ passthrough: true }) res: Response) {
    res.clearCookie('accountId');
    return { ok: true };
  }

  @Post(':id/reset-password')
  @ApiOperation({
    summary: 'Reset password (system-generated)',
    description: 'System generates a new password and sets password_expiry_time. Response includes the new password and expiry info.',
  })
  @ApiParam({ name: 'id', description: 'Account ID (UUID)' })
  @ApiBody({ type: ResetPasswordDto })
  @ApiOkResponse({ type: AccountResetPasswordResponseDto })
  @ApiBadRequestResponse({
    type: ApiErrorResponseDto,
    description: 'Invalid UUID format or password_expiry_time invalid',
    schema: {
      example: {
        statusCode: 400,
        error: 'Bad Request',
        message: 'Validation failed',
        details: [{ field: 'password_expiry_time', message: 'password_expiry_time must be a valid ISO date' }],
      },
    },
  })
  @ApiNotFoundResponse({ type: ApiErrorResponseDto, description: 'Account not found' })
  @Serialize(AccountResetPasswordResponseDto)
  resetPassword(@Param('id') id: string, @Body() body: ResetPasswordDto) {
    return this.svc.resetPassword(id, body.password_expiry_time);
  }

  @Post(':id/change-password')
  @ApiOperation({
    summary: 'Change password (user-defined)',
    description: 'New password must follow SOP. password_expiry_time is set to 3 months from now.',
  })
  @ApiParam({ name: 'id', description: 'Account ID (UUID)' })
  @ApiBody({ type: ChangePasswordDto })
  @ApiOkResponse({ type: AccountChangePasswordResponseDto })
  @ApiBadRequestResponse({
    type: ApiErrorResponseDto,
    description: 'Invalid UUID format or password complexity failed',
    schema: {
      example: {
        statusCode: 400,
        error: 'Bad Request',
        message: 'Validation failed',
        details: [{ field: 'newPassword', message: 'Password does not meet complexity rules' }],
      },
    },
  })
  @ApiNotFoundResponse({ type: ApiErrorResponseDto, description: 'Account not found' })
  @Serialize(AccountChangePasswordResponseDto)
  changePassword(@Param('id') id: string, @Body() body: ChangePasswordDto) {
    return this.svc.changePassword(id, body.newPassword);
  }

  @Patch(':id/role')
  @ApiOperation({ summary: 'Edit account role' })
  @ApiParam({ name: 'id', description: 'Account ID (UUID)' })
  @ApiBody({ type: EditRoleDto })
  @ApiOkResponse({ type: AccountEditRoleResponseDto })
  @ApiBadRequestResponse({
    type: ApiErrorResponseDto,
    description: 'Invalid UUID format or role lookup not found',
    schema: {
      example: {
        statusCode: 400,
        error: 'Bad Request',
        message: 'Validation failed',
        details: [{ field: 'id', message: 'Invalid UUID format' }],
      },
    },
  })
  @Serialize(AccountEditRoleResponseDto)
  editRole(@Param('id') id: string, @Body() body: EditRoleDto) {
    return this.svc.editRole(id, body.roleLookupId);
  }

  @Patch(':id')
  @ApiOperation({ summary: 'Edit account (username, full_name, phone_number, email, attribute)' })
  @ApiParam({ name: 'id', description: 'Account ID (UUID)' })
  @ApiBody({ type: EditAccountDto })
  @ApiOkResponse({ type: AccountEditResponseDto })
  @ApiBadRequestResponse({
    type: ApiErrorResponseDto,
    description: 'Invalid UUID format or validation failed',
    schema: {
      example: {
        statusCode: 400,
        error: 'Bad Request',
        message: 'Validation failed',
        details: [{ field: 'id', message: 'Invalid UUID format' }],
      },
    },
  })
  @ApiConflictResponse({
    type: ApiErrorResponseDto,
    description: 'Username already exists',
    schema: {
      example: {
        statusCode: 409,
        error: 'Conflict',
        message: 'Username already exists',
        details: [{ field: 'username', message: 'Username already exists' }],
      },
    },
  })
  @ApiNotFoundResponse({ type: ApiErrorResponseDto, description: 'Account not found' })
  @Serialize(AccountEditResponseDto)
  editAccount(@Param('id') id: string, @Body() body: EditAccountDto) {
    return this.svc.editAccount(id, body as any);
  }

  @Patch(':id/disable')
  @ApiOperation({ summary: 'Disable account' })
  @ApiParam({ name: 'id', description: 'Account ID (UUID)' })
  @ApiOkResponse({ type: AccountLifecycleResponseDto })
  @ApiBadRequestResponse({ type: ApiErrorResponseDto, description: 'Invalid UUID format' })
  @ApiNotFoundResponse({ type: ApiErrorResponseDto, description: 'Account not found' })
  @Serialize(AccountLifecycleResponseDto)
  disable(@Param('id') id: string) {
    return this.svc.setLifecycle(id, 'DISABLED');
  }

  @Patch(':id/enable')
  @ApiOperation({ summary: 'Enable account' })
  @ApiParam({ name: 'id', description: 'Account ID (UUID)' })
  @ApiOkResponse({ type: AccountLifecycleResponseDto })
  @ApiBadRequestResponse({ type: ApiErrorResponseDto, description: 'Invalid UUID format' })
  @ApiNotFoundResponse({ type: ApiErrorResponseDto, description: 'Account not found' })
  @Serialize(AccountLifecycleResponseDto)
  enable(@Param('id') id: string) {
    return this.svc.setLifecycle(id, 'ACTIVE');
  }

  @Delete(':id')
  @ApiOperation({ summary: 'Soft delete account (mark DELETED)' })
  @ApiParam({ name: 'id', description: 'Account ID (UUID)' })
  @ApiOkResponse({ type: AccountDeleteResponseDto })
  @ApiBadRequestResponse({ type: ApiErrorResponseDto, description: 'Invalid UUID format' })
  @ApiNotFoundResponse({ type: ApiErrorResponseDto, description: 'Account not found' })
  @Serialize(AccountDeleteResponseDto)
  delete(@Param('id') id: string) {
    return this.svc.softDelete(id);
  }
}
